Repository labstudydev/ArchitectureStudy, pull requests merged in 2019-10, with the labels that each got.

#32 AS-5 모델링수정 및 사진추가
  Parkduksung/ElevenStreetMvpSample/app/build.gradle
  Parkduksung/ElevenStreetMvpSample/app/src/main/AndroidManifest.xml
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/data/model/ProductItem.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/data/model/ProductItemCallback.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/data/model/ProductItemData.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/data/repository/ProductRepository.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/data/repository/ProductRepositoryCallback.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/data/repository/ProductRepositoryImpl.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/data/source/local/ProductLocalDataSource.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/data/source/local/ProductLocalDataSourceCallback.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/data/source/local/ProductLocalDataSourceImpl.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/data/source/remote/ProductRemoteDataSource.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/data/source/remote/ProductRemoteDataSourceCallback.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/data/source/remote/ProductRemoteDataSourceImpl.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/network/model/ProductResponse.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/view/product/OnBackPressedListener.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/view/product/ProductActivity.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/view/product/ProductFragment.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/view/product/adapter/ProductAdapter.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/view/product/presenter/ProductConstract.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/view/product/presenter/ProductContract.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/view/product/presenter/ProductPresenter.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/res/drawable/not_connect.png
  Parkduksung/ElevenStreetMvpSample/app/src/main/res/layout/activity_main.xml
  Parkduksung/ElevenStreetMvpSample/app/src/main/res/layout/fragment_layout.xml
  Parkduksung/ElevenStreetMvpSample/app/src/main/res/layout/list_layout.xml
  Parkduksung/ElevenStreetMvpSample/app/src/main/res/values/colors.xml
  Parkduksung/FBMember/app/src/main/java/user/manage/fbmember/CallBack.kt
Labels: Review Needed

#36 AS-6 DataBinding
  Parkduksung/ElevenStreetMvpSample/.gitignore
  Parkduksung/ElevenStreetMvpSample/app/build.gradle
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/view/product/ProductActivity.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/view/product/ProductFragment.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/view/product/adapter/ProductAdapter.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/res/layout/activity_main.xml
  Parkduksung/ElevenStreetMvpSample/app/src/main/res/layout/fragment_layout.xml
  Parkduksung/ElevenStreetMvpSample/app/src/main/res/layout/list_layout.xml
Labels: Answer Needed

#33 AS-5
  yeonjae22/ElevenStreetSample/app/build.gradle
  yeonjae22/ElevenStreetSample/app/src/main/AndroidManifest.xml
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/RetrofitInstance.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/ProductCallBack.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/ProductXmlPullParserHandler.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/repository/ProductRepository.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/repository/ProductRepositoryImpl.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/source/local/ProductLocalDataSource.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/source/local/ProductLocalDataSourceImpl.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/source/remote/ProductRemoteDataSource.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/source/remote/ProductRemoteDataSourceImpl.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/model/ProductItem.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/model/ProductResponse.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/network/ElevenStreetApi.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/view/presenter/ProductPresenter.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/view/product/ProductActivity.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/view/product/ProductAdapter.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/view/product/ProductFragment.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/view/product/presenter/ProductContract.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/view/product/presenter/ProductPresenter.kt
  yeonjae22/ElevenStreetSample/app/src/main/res/drawable/back.png
  yeonjae22/ElevenStreetSample/app/src/main/res/layout/activity_product.xml
  yeonjae22/ElevenStreetSample/app/src/main/res/layout/fragment_product.xml
  yeonjae22/ElevenStreetSample/app/src/main/res/layout/list_item.xml
Labels: Answer Needed

#37 AS-7 MVVM 적용
  yeonjae22/ElevenStreetSample/app/src/main/AndroidManifest.xml
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/source/remote/ProductRemoteDataSourceImpl.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/ext/ImageViewExt.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/view/product/ProductActivity.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/view/product/ProductAdapter.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/view/product/ProductFragment.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/viewmodel/ProductViewModel.kt
  yeonjae22/ElevenStreetSample/app/src/main/res/layout/activity_product.xml
  yeonjae22/ElevenStreetSample/app/src/main/res/layout/fragment_product.xml
  yeonjae22/ElevenStreetSample/app/src/main/res/layout/list_item.xml
Labels: Merge Needed

#38 AS-4 MVP, DataBinding 적용
  Lsunae/ElevenStreetSample/.idea/codeStyles/Project.xml
  Lsunae/ElevenStreetSample/app/build.gradle
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/Callback.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/model/ProductItem.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/repository/ProductRepository.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/repository/ProductRepositoryImpl.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/source/local/ProductLocalDataSource.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/source/local/ProductLocalDataSourceImpl.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/source/remote/ProductRemoteDataSource.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/source/remote/ProductRemoteDataSourceImpl.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/ext/ContextExt.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/ext/ImageViewExt.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/network/model/ProductResponse.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/view/product/ProductActivity.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/view/product/adapter/ProductAdapter.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/view/product/presenter/ProductContract.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/view/product/presenter/ProductPresenter.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/viewmodel/ProductViewModel.kt
  Lsunae/ElevenStreetSample/app/src/main/res/drawable-v24/not_connect.png
  Lsunae/ElevenStreetSample/app/src/main/res/layout/activity_main.xml
  Lsunae/ElevenStreetSample/app/src/main/res/layout/list_item.xml
  Lsunae/ElevenStreetSample/app/src/main/res/values/strings.xml
  Lsunae/ElevenStreetSample/build.gradle
  Lsunae/FBMember/.idea/workspace.xml
Labels: Review Needed

#40 AS-7 MVVM
  ElevenStreetSample_MVP_modify/.idea/ElevenStreetSample_MVP_modify.iml
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/view/product/ProductActivity.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/view/product/presenter/ProductPresenter.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/viewmodel/ProductViewModel.kt
  WS_MVVM/wswon/ElevenStreetSample/app/app.iml
Labels: Review Needed
