Repository labstudydev/ArchitectureStudy, pull requests merged in 2019-09, with the labels that each got.

#18 AS-2
  Parkduksung/ElevenStreetSample/.gitignore
  Parkduksung/ElevenStreetSample/.idea/codeStyles/Project.xml
  Parkduksung/ElevenStreetSample/.idea/codeStyles/codeStyleConfig.xml
  Parkduksung/ElevenStreetSample/.idea/encodings.xml
  Parkduksung/ElevenStreetSample/.idea/gradle.xml
  Parkduksung/ElevenStreetSample/.idea/misc.xml
  Parkduksung/ElevenStreetSample/.idea/runConfigurations.xml
  Parkduksung/ElevenStreetSample/app/.gitignore
  Parkduksung/ElevenStreetSample/app/build.gradle
  Parkduksung/ElevenStreetSample/app/proguard-rules.pro
  Parkduksung/ElevenStreetSample/app/src/androidTest/java/com/exam/elevenstreet/ExampleInstrumentedTest.kt
  Parkduksung/ElevenStreetSample/app/src/main/AndroidManifest.xml
  Parkduksung/ElevenStreetSample/app/src/main/assets/ElevenStreetOpenApiService.xml
  Parkduksung/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/ProductAdapter.kt
  Parkduksung/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/Repository/ProductRepository.kt
  Parkduksung/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/model/ProductResponse.kt
  Parkduksung/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/source/ProductXmlPullParserHandler.kt
  Parkduksung/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/util/App.kt
  Parkduksung/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/view/base/MainActivity.kt
  Parkduksung/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/view/product/ProductActivity.kt
  Parkduksung/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/view/product/adapter/ProductAdapter.kt
  Parkduksung/ElevenStreetSample/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  Parkduksung/ElevenStreetSample/app/src/main/res/drawable/ic_launcher_background.xml
  Parkduksung/ElevenStreetSample/app/src/main/res/layout/activity_main.xml
  Parkduksung/ElevenStreetSample/app/src/main/res/layout/list_layout.xml
  Parkduksung/ElevenStreetSample/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Parkduksung/ElevenStreetSample/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Parkduksung/ElevenStreetSample/app/src/main/res/mipmap-hdpi/ic_launcher.png
  Parkduksung/ElevenStreetSample/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  Parkduksung/ElevenStreetSample/app/src/main/res/mipmap-mdpi/ic_launcher.png
  Parkduksung/ElevenStreetSample/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  Parkduksung/ElevenStreetSample/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  Parkduksung/ElevenStreetSample/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  Parkduksung/ElevenStreetSample/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  Parkduksung/ElevenStreetSample/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  Parkduksung/ElevenStreetSample/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  Parkduksung/ElevenStreetSample/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  Parkduksung/ElevenStreetSample/app/src/main/res/values/colors.xml
  Parkduksung/ElevenStreetSample/app/src/main/res/values/strings.xml
  Parkduksung/ElevenStreetSample/app/src/main/res/values/styles.xml
  Parkduksung/ElevenStreetSample/app/src/main/res/xml/network_security_config.xml
  Parkduksung/ElevenStreetSample/app/src/test/java/com/exam/elevenstreet/ExampleUnitTest.kt
  Parkduksung/ElevenStreetSample/build.gradle
  Parkduksung/ElevenStreetSample/gradle.properties
  Parkduksung/ElevenStreetSample/gradle/wrapper/gradle-wrapper.jar
  Parkduksung/ElevenStreetSample/gradle/wrapper/gradle-wrapper.properties
  Parkduksung/ElevenStreetSample/gradlew
  Parkduksung/ElevenStreetSample/gradlew.bat
  Parkduksung/ElevenStreetSample/settings.gradle
Labels: Merge Needed, Review Needed

#19 AS-2
  Lsunae/ElevenStreetSample/.gitignore
  Lsunae/ElevenStreetSample/.idea/codeStyles/Project.xml
  Lsunae/ElevenStreetSample/.idea/codeStyles/codeStyleConfig.xml
  Lsunae/ElevenStreetSample/.idea/encodings.xml
  Lsunae/ElevenStreetSample/.idea/gradle.xml
  Lsunae/ElevenStreetSample/.idea/misc.xml
  Lsunae/ElevenStreetSample/.idea/runConfigurations.xml
  Lsunae/ElevenStreetSample/.idea/vcs.xml
  Lsunae/ElevenStreetSample/app/.gitignore
  Lsunae/ElevenStreetSample/app/build.gradle
  Lsunae/ElevenStreetSample/app/proguard-rules.pro
  Lsunae/ElevenStreetSample/app/src/androidTest/java/com/exam/elevenstreet/ExampleInstrumentedTest.kt
  Lsunae/ElevenStreetSample/app/src/main/AndroidManifest.xml
  Lsunae/ElevenStreetSample/app/src/main/assets/ElevenStreetOpenApiService.xml
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/ElevenStreetApi.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/RetrofitInstance.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/ProductXmlPullParserHandler.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/model/ProductResponse.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/view/product/MainActivity.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/view/product/adapter/ProductAdapter.kt
  Lsunae/ElevenStreetSample/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  Lsunae/ElevenStreetSample/app/src/main/res/drawable/ic_launcher_background.xml
  Lsunae/ElevenStreetSample/app/src/main/res/layout/activity_main.xml
  Lsunae/ElevenStreetSample/app/src/main/res/layout/list_item.xml
  Lsunae/ElevenStreetSample/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Lsunae/ElevenStreetSample/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Lsunae/ElevenStreetSample/app/src/main/res/mipmap-hdpi/ic_launcher.png
  Lsunae/ElevenStreetSample/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  Lsunae/ElevenStreetSample/app/src/main/res/mipmap-mdpi/ic_launcher.png
  Lsunae/ElevenStreetSample/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  Lsunae/ElevenStreetSample/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  Lsunae/ElevenStreetSample/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  Lsunae/ElevenStreetSample/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  Lsunae/ElevenStreetSample/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  Lsunae/ElevenStreetSample/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  Lsunae/ElevenStreetSample/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  Lsunae/ElevenStreetSample/app/src/main/res/values/colors.xml
  Lsunae/ElevenStreetSample/app/src/main/res/values/strings.xml
  Lsunae/ElevenStreetSample/app/src/main/res/values/styles.xml
  Lsunae/ElevenStreetSample/app/src/main/res/xml/network_security_config.xml
  Lsunae/ElevenStreetSample/app/src/test/java/com/exam/elevenstreet/ExampleUnitTest.kt
  Lsunae/ElevenStreetSample/build.gradle
  Lsunae/ElevenStreetSample/gradle.properties
  Lsunae/ElevenStreetSample/gradle/wrapper/gradle-wrapper.jar
  Lsunae/ElevenStreetSample/gradle/wrapper/gradle-wrapper.properties
  Lsunae/ElevenStreetSample/gradlew
  Lsunae/ElevenStreetSample/gradlew.bat
  Lsunae/ElevenStreetSample/settings.gradle
Labels: Merge Needed

#21 AS-1 회원관리
  jeongjaein/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/ElevenStreetApi.kt
  jeongjaein/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/ProductActivity.kt
  jeongjaein/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/ProductResponse.kt
  jeongjaein/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/RetrofitInstance.kt
  jeongjaein/FBMember/.gitignore
  jeongjaein/FBMember/.idea/codeStyles/Project.xml
  jeongjaein/FBMember/.idea/codeStyles/codeStyleConfig.xml
  jeongjaein/FBMember/.idea/runConfigurations.xml
  jeongjaein/FBMember/app/.gitignore
  jeongjaein/FBMember/app/build.gradle
  jeongjaein/FBMember/app/google-services.json
  jeongjaein/FBMember/app/proguard-rules.pro
  jeongjaein/FBMember/app/src/androidTest/java/user/manage/fbmember/ExampleInstrumentedTest.kt
  jeongjaein/FBMember/app/src/main/AndroidManifest.xml
  jeongjaein/FBMember/app/src/main/java/user/manage/fbmember/AccountManager.kt
  jeongjaein/FBMember/app/src/main/java/user/manage/fbmember/CreateActivity.kt
  jeongjaein/FBMember/app/src/main/java/user/manage/fbmember/LoginActivity.kt
  jeongjaein/FBMember/app/src/main/java/user/manage/fbmember/ModifyActivity.kt
  jeongjaein/FBMember/app/src/main/java/user/manage/fbmember/MypageActivity.kt
  jeongjaein/FBMember/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  jeongjaein/FBMember/app/src/main/res/drawable/ic_launcher_background.xml
  jeongjaein/FBMember/app/src/main/res/layout/activity_create.xml
  jeongjaein/FBMember/app/src/main/res/layout/activity_login.xml
  jeongjaein/FBMember/app/src/main/res/layout/activity_modify.xml
  jeongjaein/FBMember/app/src/main/res/layout/activity_mypage.xml
  jeongjaein/FBMember/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  jeongjaein/FBMember/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  jeongjaein/FBMember/app/src/main/res/mipmap-hdpi/ic_launcher.png
  jeongjaein/FBMember/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  jeongjaein/FBMember/app/src/main/res/mipmap-mdpi/ic_launcher.png
  jeongjaein/FBMember/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  jeongjaein/FBMember/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  jeongjaein/FBMember/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  jeongjaein/FBMember/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  jeongjaein/FBMember/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  jeongjaein/FBMember/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  jeongjaein/FBMember/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  jeongjaein/FBMember/app/src/main/res/values/colors.xml
  jeongjaein/FBMember/app/src/main/res/values/strings.xml
  jeongjaein/FBMember/app/src/main/res/values/styles.xml
  jeongjaein/FBMember/app/src/test/java/user/manage/fbmember/ExampleUnitTest.kt
  jeongjaein/FBMember/build.gradle
  jeongjaein/FBMember/gradle.properties
  jeongjaein/FBMember/gradle/wrapper/gradle-wrapper.jar
  jeongjaein/FBMember/gradle/wrapper/gradle-wrapper.properties
  jeongjaein/FBMember/gradlew
  jeongjaein/FBMember/gradlew.bat
  jeongjaein/FBMember/settings.gradle
Labels: Merge Needed

#22 AS-3
  yeonjae22/ElevenStreetSample/app/src/main/AndroidManifest.xml
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/ProductLocalDataSource.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/ProductRemoteDataSource.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/ProductRepository.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/ext/ContextExt.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/network/RetrofitInstance.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/util/App.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/view/product/ProductActivity.kt
  yeonjae22/ElevenStreetSample/app/src/main/res/layout/activity_product.xml
  yeonjae22/FBMember/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  yeonjae22/FBMember/.idea/caches/build_file_checksums.ser
  yeonjae22/FBMember/.idea/workspace.xml
Labels: Merge Needed, Review Needed

#30 AS-4
  Parkduksung/ElevenStreetMvpSample/.gitignore
  Parkduksung/ElevenStreetMvpSample/.idea/codeStyles/Project.xml
  Parkduksung/ElevenStreetMvpSample/.idea/codeStyles/codeStyleConfig.xml
  Parkduksung/ElevenStreetMvpSample/.idea/encodings.xml
  Parkduksung/ElevenStreetMvpSample/.idea/gradle.xml
  Parkduksung/ElevenStreetMvpSample/.idea/misc.xml
  Parkduksung/ElevenStreetMvpSample/.idea/runConfigurations.xml
  Parkduksung/ElevenStreetMvpSample/.idea/vcs.xml
  Parkduksung/ElevenStreetMvpSample/app/.gitignore
  Parkduksung/ElevenStreetMvpSample/app/build.gradle
  Parkduksung/ElevenStreetMvpSample/app/proguard-rules.pro
  Parkduksung/ElevenStreetMvpSample/app/src/androidTest/java/com/exam/elevenstreet/ExampleInstrumentedTest.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/AndroidManifest.xml
  Parkduksung/ElevenStreetMvpSample/app/src/main/assets/ElevenStreetOpenApiService.xml
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/data/parser/ProductXmlPullParserHandler.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/data/repository/ProductRepository.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/data/repository/ProductRepositoryImpl.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/data/source/local/ProductLocalDataSource.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/data/source/local/ProductLocalDataSourceImpl.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/data/source/remote/ProductRemoteDataSource.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/data/source/remote/ProductRemoteDataSourceImpl.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/ext/ContextExt.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/network/RetrofitInstance.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/network/api/ElevenStreetApi.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/network/model/ProductResponse.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/util/App.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/view/product/ProductActivity.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/view/product/adapter/ProductAdapter.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/view/product/presenter/ProductConstract.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/java/com/exam/elevenstreet/view/product/presenter/ProductPresenter.kt
  Parkduksung/ElevenStreetMvpSample/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  Parkduksung/ElevenStreetMvpSample/app/src/main/res/drawable/ic_launcher_background.xml
  Parkduksung/ElevenStreetMvpSample/app/src/main/res/layout/activity_main.xml
  Parkduksung/ElevenStreetMvpSample/app/src/main/res/layout/list_layout.xml
  Parkduksung/ElevenStreetMvpSample/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Parkduksung/ElevenStreetMvpSample/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Parkduksung/ElevenStreetMvpSample/app/src/main/res/mipmap-hdpi/ic_launcher.png
  Parkduksung/ElevenStreetMvpSample/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  Parkduksung/ElevenStreetMvpSample/app/src/main/res/mipmap-mdpi/ic_launcher.png
  Parkduksung/ElevenStreetMvpSample/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  Parkduksung/ElevenStreetMvpSample/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  Parkduksung/ElevenStreetMvpSample/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  Parkduksung/ElevenStreetMvpSample/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  Parkduksung/ElevenStreetMvpSample/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  Parkduksung/ElevenStreetMvpSample/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  Parkduksung/ElevenStreetMvpSample/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  Parkduksung/ElevenStreetMvpSample/app/src/main/res/values/colors.xml
  Parkduksung/ElevenStreetMvpSample/app/src/main/res/values/strings.xml
  Parkduksung/ElevenStreetMvpSample/app/src/main/res/values/styles.xml
  Parkduksung/ElevenStreetMvpSample/app/src/main/res/xml/network_security_config.xml
  Parkduksung/ElevenStreetMvpSample/app/src/test/java/com/exam/elevenstreet/ExampleUnitTest.kt
  Parkduksung/ElevenStreetMvpSample/build.gradle
  Parkduksung/ElevenStreetMvpSample/gradle.properties
  Parkduksung/ElevenStreetMvpSample/gradle/wrapper/gradle-wrapper.jar
  Parkduksung/ElevenStreetMvpSample/gradle/wrapper/gradle-wrapper.properties
  Parkduksung/ElevenStreetMvpSample/gradlew
  Parkduksung/ElevenStreetMvpSample/gradlew.bat
  Parkduksung/ElevenStreetMvpSample/settings.gradle
Labels: Merge Needed

#31 AS-4
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/ProductRemoteDataSource.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/ProductRepository.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/view/presenter/ProductContract.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/view/presenter/ProductPresenter.kt
  yeonjae22/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/view/product/ProductActivity.kt
Labels: Review Needed

#24 AS-3
  Lsunae/ElevenStreetSample/app/src/main/AndroidManifest.xml
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/RetrofitInstance.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/Callback.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/model/ProductItem.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/parser/ProductXmlPullParserHandler.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/repository/ProductRepository.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/source/local/ProductLocalDataSource.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/data/source/remote/ProductRemoteDataSource.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/ext/ContextExt.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/network/api/ElevenStreetApi.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/network/model/ProductResponse.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/view/product/App.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/view/product/MainActivity.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/view/product/ProductActivity.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/view/product/adapter/ProductAdapter.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/view/product/presenter/ProductContract.kt
  Lsunae/ElevenStreetSample/app/src/main/java/com/exam/elevenstreet/view/product/presenter/ProductPresenter.kt
  Lsunae/ElevenStreetSample/app/src/main/res/layout/activity_main.xml
Labels: Answer Needed, Mentor Needed
